PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

CONSTRUCT {
  ?class a rdfs:Class ;
         rdfs:label ?lab .
}
WHERE {
  GRAPH <https://data.jobsandskills.gov.au/graph/skills-sparql/combined> {
    ?s a ?class .
    FILTER(isIRI(?class))

    OPTIONAL { ?class rdfs:label ?l1 . FILTER(langMatches(lang(?l1), "en")) }
    OPTIONAL { ?class skos:prefLabel ?l2 . FILTER(langMatches(lang(?l2), "en")) }
    BIND(COALESCE(?l1, ?l2, STRLANG(REPLACE(STR(?class), '^.*[#/]', ''), 'en')) AS ?lab)
  }
}
