PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

CONSTRUCT {
  ?cs a skos:ConceptScheme ;
      skos:prefLabel ?pl .
}
WHERE {
  GRAPH <https://data.jobsandskills.gov.au/graph/skills-sparql/combined> {
    ?cs a skos:ConceptScheme .
    FILTER(!STRSTARTS(STR(?cs), "http://data.europa.eu/esco/concept-scheme/"))
    ?cs skos:prefLabel ?pl .
    FILTER(langMatches(lang(?pl), "en"))
  }
}
