PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX tgaqual: <https://training.gov.au/tgaQualifications/>

SELECT ?subject ?predicate (tgaqual:ICT30120 AS ?object)
WHERE {
  { ?predicate dcterms:isReferencedBy ?object . }
  UNION
  { ?predicate dcterms:isRequiredBy ?object . }
}
