SELECT ?s ?p ?o
WHERE{
VALUES ?o{<https://training.gov.au/tgaQualifications/ICT30120>}
?s ?p ?o.
FILTER(?p=<http://purl.org/dc/terms/isReferencedBy>||?p=<http://purl.org/dc/terms/isRequiredBy>)
}


#No terminal matches ' ' in the current parser context, at line 1 col 16 SELECT ?s ?p ?o ^ Expected one of: * __ANON_1 * LEFT_PARENTHESIS * __ANON_4 * VAR1 * VAR2 * LEFT_CURLY_BRACE
